# two player games with Nashpy

Nashpy is a python library for **game theory**, specifically "*for the computation of equilibria in 2 player strategic form games.*"

Game theory is "*the study of strategic interactions between rational agents. This means that it is the study of interactions when the involved parties try and do what is best from their point of view.*" - from the Nashpy [Introduction to Game Theory](https://nashpy.readthedocs.io/en/stable/tutorial/index.html#introduction-to-game-theory)


* ***Nashpy documentation:*** https://nashpy.readthedocs.io/en/stable/


## more game theory:

* Game Theory Concepts In Python Part 1: https://towardsdatascience.com/game-theory-in-python-with-nashpy-cb5dceab262c


* Game Theory Concepts In Python Part 2:https://towardsdatascience.com/game-theory-concepts-with-application-in-python-using-axel-rod-part-2-8ae5e10e09a0

### prisoner's dilemma matrix:

![picture](https://drive.google.com/uc?id=1fw7j7O8XLGQR3Rt_c9UK_PE6KgLsFeEw)


In [1]:
# Import packages
!pip install nashpy
!pip install axelrod

import nashpy as nash
import numpy as np

     |████████████████████████████████| 17.1 MB 192 kB/s eta 0:00:01    |████████████▎                   | 6.6 MB 6.2 MB/s eta 0:00:02
     |████████████████████████████████| 33.8 MB 47 kB/s s eta 0:00:01     |████████████████▏               | 17.0 MB 35.7 MB/s eta 0:00:01    |█████████████████████████████▍  | 30.9 MB 23.7 MB/s eta 0:00:01    |██████████████████████████████  | 31.5 MB 23.7 MB/s eta 0:00:01
     |████████████████████████████████| 191 kB 3.2 MB/s eta 0:00:01
     |████████████████████████████████| 575 kB 40.7 MB/s eta 0:00:01
     |████████████████████████████████| 661 kB 6.5 MB/s eta 0:00:01
     |████████████████████████████████| 11.8 MB 9.4 MB/s eta 0:00:01
     |████████████████████████████████| 12.2 MB 8.7 MB/s eta 0:00:01
     |████████████████████████████████| 1.1 MB 10.4 MB/s eta 0:00:01
     |████████████████████████████████| 78 kB 2.3 MB/s  eta 0:00:01
     |████████████████████████████████| 140 kB 5.4 MB/s eta 0:00:01
     |████████████████████████████████| 55

In [2]:
# payoff matrix

# P1 is the row player
P1 = np.array([[8,1],[15,3]]) 

# P2 is the column player
P2 = np.array([[8,15],[1,3]])

# pd stands for prisoners dilemma
pd = nash.Game(P1,P2)

# use `pd` to check game
pd


Bi matrix game with payoff matrices:

Row player:
[[ 8  1]
 [15  3]]

Column player:
[[ 8 15]
 [ 1  3]]

### two player game: players as *A* and *B*

***matrix:*** 

![picture](https://drive.google.com/uc?id=1eHhyXZVZWQ3oPto4qcbL1EefxUsWq4bp)


In [4]:
# pA is row player
pA = np.array([[5,17],[14,12]])

# pB is column player
pB = np.array([[15,16],[2,8]])

gm = nash.Game(pA,pB)

gm

Bi matrix game with payoff matrices:

Row player:
[[ 5 17]
 [14 12]]

Column player:
[[15 16]
 [ 2  8]]