# zero sum games

in zero sum games, the gain of one player is ***exactly*** the loss of the other player.

they're called zero sum because summing up the payoffs for any combination of strategies will result in zero. in other words, mathematically the payoff to one player is the *compliment* of payoff to the other player.

because of this property, it's only necessary to code the payoffs for one player into an array. the library automatically interprets this as a zero sum game.

for more on game theory & pure strategy Nash equilibria check out "*Chapter 2 - Game Theory for Infrastructure Security: The Power of Intent-Based Adversary Models*" from 

* Alireza Shamsoshoara, Ashwija Korenda, Fatemeh Afghah, Sherali Zeadally, A survey on physical unclonable function (PUF)-based security solutions for Internet of Things,Computer Networks,Volume 183,2020,107593,ISSN 1389-1286, https://doi.org/10.1016/j.comnet.2020.107593.

also check out:

* [Nashpy Introduction to Game Theory](https://nashpy.readthedocs.io/en/stable/tutorial/index.html#introduction-to-game-theory) 

and the

* [Nashpy documentation](https://nashpy.readthedocs.io/en/stable/) 

* [Numpy documentation](https://numpy.org/doc/)


In [1]:
# Import packages
!pip install nashpy

import nashpy as nash
import numpy as np


**matching the pennies game:**

![picture](https://drive.google.com/uc?id=1DJhLFiRbUah8Cvku03oGP5C2eFuDPxBQ)

*adapted from Coursera*

In [25]:
P5 = np.array([[1,-1],[-1,1]])
mp = nash.Game(P5)
mp

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [27]:
equilibria = mp.support_enumeration()

for eq in equilibria:
    
    print(eq)

(array([0.5, 0.5]), array([0.5, 0.5]))



* this is called the *Mixed Strategy Nash Equilibrium* for this game

* probabilities will not always be 50/50; depending on the chaos & the game 

### find the solution for the zero sum game 'zs'

* payoff matrix - np.array([[5, -6.5], [-2.5, 7]]) 
* players *Z1* and *Z2*

In [28]:
Z1 = np.array([[5,-6.5],[-2.5,7]])

zs = nash.Game(Z1)

zs

Zero sum game with payoff matrices:

Row player:
[[ 5.  -6.5]
 [-2.5  7. ]]

Column player:
[[-5.   6.5]
 [ 2.5 -7. ]]

In [30]:
equilibria = zs.support_enumeration()

for eq in equilibria:
    
    print(eq)

(array([0.45238095, 0.54761905]), array([0.64285714, 0.35714286]))


this is the mixed strategy Nash equilibrium for the game *`zs`*.

***interpreting results:***

if the game is played 100 times, and 

> * Z1 plays S1 (strategy 1) 45 times, and S2 the remaining 55 times
>
> __and__ 
> * Z2 plays S1 64 times, and plays S2 the remaining 36 times

...they will obtain the same expected payoffs.